### ISSUE TITLE
Design concept

### ISSUE THREAD

**Issue by SheepTester** [Orbiit/gunn-remake#10]
So I suppose we're moving on to making la ĉefretpaĝo so we know what we actually need to design.

Features the current Gunn ĉefretpaĝo has that I think we should incorporate into our redesign in some way:

- [x] image carousel (see #8) which can be that huge image modern sites have for some reason ([example](https://host.gwiddlefoundation.org.uk/) and [another example](https://themes.materializecss.com/pages/dark-theme))
- [x] events calendar (it only has to list a few items; there can be a view more option linking to a full-sized calendar)
- [x] recent news/announcements
- [x] a very easy-to-access "Crisis Resources" link

**Comment by SheepTester** [comment]
We also need the login button

**Comment by heaucques** [comment]
What would the redesigned images be like though
I don't camera

**Comment by SheepTester** [comment]
We find the place roughly where the picture was taken and use someone's phone to take a picture

Maybe if someone has a Google pixel we can use its fancy camera with its HD blur; I think Nick has one

After that we apply filters so it looks like we aren't in a drought and then crop to 16:9 (both of which I can do on iOS relatively easily)

**Comment by heaucques** [comment]
Got it
So how do we obtain the product named "Nick"

**Comment by SheepTester** [comment]
We don't need Nick; we can use anyone's phone. But this Nick (a nickname for someone IRL) person product demonstrated to me one day in the past the special blur camera feature the Pixel has:

I think it's a camera mode, and then he takes a picture, then the screen says to move the camera up (so it knows depth) and he does and suddenly after a bit of processing time there's an object that is focused and the background is blurred high-definitionwise

**Comment by heaucques** [comment]
Aperture can affect that but the fact that the google pixel can do that with software/hardware is impressive

**Comment by heaucques** [comment]
attempted to smash them all together
need feedback

**Comment by SheepTester** [comment]
Ayy thanks. I'll start implementing them soon.

For now, I'm going to close this
