### ISSUE TITLE
"Gunn High School" not vertically aligned

### ISSUE THREAD

**Issue by SheepTester** [Orbiit/gunn-remake#11]
When the big title text wraps (usually only on smaller screens), it isn't vertically aligned. This was probably caused when I reverted back to the non-flexbox workaround for vertical alignment (because Safari 🙄). I might revert back to the flexbox workaround and see what I can do for Safari

**Comment by heaucques** [comment]
why not use `transform` to center it in the middle of the screen
but then it needs to be a child of an already centered element or something the size of the screen

**Comment by SheepTester** [comment]
I've switched back to flex which works well on MacOS Safari. It better work on iOS

**Comment by SheepTester** [comment]
It works on iOS! All fixed!
