### ISSUE TITLE
Login Button Location

### ISSUE THREAD

**Issue by MajikalExplosions** [Orbiit/gunn-remake#13]
The login button location is awkward on t04.html; perhaps we should move it to the top?

**Comment by SheepTester** [comment]
@Velosify can design some concept art of the navbar with the login button.

Should the login button be an icon (it'll make making the site responsive much easier) or a label (it'll make the purpose of the button clearer)?

**Comment by SheepTester** [comment]
`t01` and `t04` now have the login button at the top. `t03` hasn't been edited yet, so if someone wants they can fix it.

It's currently the material design unlocked button with no hover effect other than `cursor: pointer;`, but I'm closing this issue now. If someone has a problem with that they can reopen this or make a new issue
