### ISSUE TITLE
t05.html is calling t10.css

### ISSUE THREAD

**Issue by SheepTester** [Orbiit/gunn-remake#14]
@MajikalExplosions did you initially make it t10.css and then changed it to t05.css last minute?

[t05.html](https://orbiit.github.io/gunn-remake/templates/t05.html)'s CSS doesn't show because
```html
...
<link rel="stylesheet" href="t10.css">
...
```

**Comment by MajikalExplosions** [comment]
Eh
I fixed that a long time ago
