### ISSUE TITLE
Henry

### ISSUE THREAD

**Issue by PooleHenry** [Orbiit/gunn-remake#15]
I am Henry
Fix it pls

**Comment by SheepTester** [comment]
You're lacking a **punctuation mark** at the end of your sentence; declarative sentences typically end in a full stop.

> I am Henry.

**Comment by heaucques** [comment]
> You're lacking a punctuation mark at the end of your sentence; declarative sentences typically end in a full stop.

Henry you're invited
*doesn't use punctuation mark*

**Comment by SheepTester** [comment]
@Velosify I've been trying to read your sentence, but I'm not sure when to stop.

**Comment by heaucques** [comment]
@SheepTester im sorry have you been reading the whole source code i will be leaving out all punctuation out of this phrase
