### ISSUE TITLE
do ni bezonas ankaŭ ĉefan koloron

### ISSUE THREAD

**Issue by SheepTester** [Orbiit/gunn-remake#2]
we have a few options:
Gunn's original; [`#C01919`](https://sheeptester.github.io/colour#C01919)
userstyle's; [`#EC3E35`](https://sheeptester.github.io/colour#EC3E35)

_ooh Github gives colours; you can still click the links to see the colours biggerly though_

**Comment by heaucques** [comment]
I prefer userstyle's red or `#F44336`

**Comment by SheepTester** [comment]
Material design red? Sure. It also comes with lighter and darker shades
