### ISSUE TITLE
t04 Nonexistent

### ISSUE THREAD

**Issue by heaucques** [Orbiit/gunn-remake#21]
Is t04.html nonexistent
It seems to be deleted
[https://orbiit.github.io/gunn-remake/templates/t04.html](url) leads to a 404 page

**Comment by PooleHenry** [comment]
Doesn't seem to show up for me either.

**Comment by SheepTester** [comment]
lol I moved it, if you checked the commit history

**Comment by heaucques** [comment]
@SheepTester Yes I noticed but not in commits

**Comment by SheepTester** [comment]
Btw if you couldn't find it it's now at https://orbiit.github.io/gunn-remake/

okthisisresolvedbye
