### ISSUE TITLE
Navigation bar no está worky 

### ISSUE THREAD

**Issue by SheepTester** [Orbiit/gunn-remake#3]
I am on the iPad and by touching the items.... IT NO WORKY

That might be because it doesn't have a `tabindex` or something. Maybe I'll have to use some JAVASCRIPT 😮

Phones probably won't experience this issue because there's already JavaScript for the menu button that appears thanks to the "responsiveness"

**Comment by SheepTester** [comment]
Maybe it's because the hover effect doesn't work well for touch users; the menu button indeed works but accessing the submenus doesn't

**Comment by heaucques** [comment]
Really

Is it a problem with psuedo elements?

**Comment by SheepTester** [comment]
@Velosify no I'm pretty sure it has to do with the `:hover`

Buttons and links work, though I'm not sure if it's because they're expected to be clickable or if it's because I also specified `:focus`

**Comment by heaucques** [comment]
On mobile there is no such thing as `:hover`
That may be why
not sure whether `:focus` helps or makes the problem worse

**Comment by SheepTester** [comment]
`:focus` helps most likely

On Windows 10 touch does trigger `:hover`; maybe I can make a very hacky fix and give everything a "hover" class if an element is tapped on.
That'll make all my CSS ugly, but whatever

**Comment by heaucques** [comment]
Any way to target only mobile? maaaaaybeeeee?

**Comment by SheepTester** [comment]
That's a terrible solution. What about touch screen computers?

**Comment by heaucques** [comment]
True
So just more failsafes

**Comment by SheepTester** [comment]
oops I thought this was the `<a>` issue
