### ISSUE TITLE
Destruction of Buildings

### ISSUE THREAD

**Issue by heaucques** [Orbiit/gunn-remake#4]
`<a>` tag not getting targeted for the underline animation

**Comment by SheepTester** [comment]
It's because the `<a>` tag is on _pluraj_ lines; the special underline doesn't know how to deal with that.

We have two options:

1. cry
2. maybe we could have two under-- nah

**Comment by heaucques** [comment]
idk how to target them separately so the only option left is to cry

**Comment by heaucques** [comment]
The main problem is detecting the multiple lines

**Comment by heaucques** [comment]
In t03 its actually very convenient for the links and they are both on one single line

**Comment by SheepTester** [comment]
Please make more useful title

**Comment by SheepTester** [comment]
@Velosify no it's not better; it's only for your screen size. If you resize the window the paragraphs wrap differently

Fortunately the Gunn website doesn't have much links within paragraphs

**Comment by SheepTester** [comment]
"Meh"
