### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by heaucques** [Orbiit/gunn-remake#7]
DO WE NEED CLOUD OR SOMETHING TO ACCESS/HOLD STUFF

**Comment by heaucques** [comment]
also the comment section (if we're having one)

**Comment by SheepTester** [comment]
No, we've decided from the start that there's going to be ZERO functionality; it's just a design concept and the only JavaScript there is is to deal with the silliness of touchscreens.

**Comment by heaucques** [comment]
I see
